// @ts-check

// The published `./core/search` entry point. The server imports the
// shared allowlist, matcher, and hit shapes through this specifier
// (LLP 0264 #shared), so the exports map entry is the contract, not an
// implementation detail: without it there is nothing for the other repo
// to import through.

import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..')
const pkg = JSON.parse(fs.readFileSync(path.join(repoRoot, 'package.json'), 'utf8'))

test('package.json publishes ./core/search the way it publishes ./core/query', () => {
  assert.deepEqual(pkg.exports['./core/search'], {
    types: './types/core/search/index.d.ts',
    import: './src/core/search/index.js',
  })
  // The types path is generated by `npm run build:types` into the parallel
  // `types/` tree, exactly like its sibling entries.
  assert.equal(
    Object.keys(pkg.exports['./core/search']).join(),
    Object.keys(pkg.exports['./core/query']).join(),
  )
  assert.ok(fs.existsSync(path.join(repoRoot, 'src/core/search/index.js')))
  assert.ok(fs.existsSync(path.join(repoRoot, 'src/core/search/types.d.ts')))
})

test('src/ and types/ are both in the published file set', () => {
  assert.ok(pkg.files.includes('src/'))
  assert.ok(pkg.files.includes('types/'))
})

test('the entry point resolves and carries the shared surface', async () => {
  const mod = await import('hypaware/core/search')
  assert.deepEqual(Object.keys(mod).sort(), [
    'MAX_MATCH_COLUMNS',
    'MAX_QUERY_LENGTH',
    'SCAN_COLUMNS',
    'SEARCHABLE_COLUMNS',
    'SNIPPET_AFTER',
    'SNIPPET_BEFORE',
    'compileMatcher',
    'makeSnippet',
  ])
  assert.equal(mod.compileMatcher('needle', false).test('a Needle'), true)
})
