export type {
  ConfigRegistry,
  ConfigSectionRegistration,
  ConfigValidationContext,
  ValidationResult,
  ValidationError,
  HypAwareV2Config,
  CollectivusV2Config,
  PluginConfigInstance,
  SinkConfigInstance,
  BlobSinkConfigInstance,
  RequestSinkConfigInstance,
  SinkInstanceConfig,
  QueryConfig,
  QueryCacheConfig,
  QueryCacheRetentionConfig,
} from '../../../collectivus-plugin-kernel-types'
