export type {
  QueryRegistry,
  DatasetRegistration,
  DatasetSchema,
  ColumnSpec,
  DatasetDiscoveryContext,
  QueryPartition,
  DatasetRefreshContext,
  DatasetRefreshResult,
  DatasetDataSourceContext,
  QueryScope,
  AsyncDataSource,
  ScanOptions,
  ScanResults,
  QueryStorageService,
} from '../../../hypaware-plugin-kernel-types.d.ts'
